### ISSUE TITLE
✨[Feature] 添加Enchant 附魔功能

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#2]
官方WIKI：https://rokuko.gitbook.io/azureflow

### 反馈须知
- [X] 已查阅wiki不存在该功能

### 功能描述
> 请描述您的想法，该功能的意义、作用

建议提供相关配置项，支持快速将"附魔"写入af物品

衍生出的两个问题：

1. 填写附魔ID采用 **mc命名空间** 还是 **bukkit枚举** （两者ID有较大差异）
2. 附魔配置项归属问题（**display**、**internal**、**data**、其他）

建议方案，或许可以新增一个配置项properties，然后将enchant置于properties的下级
properties可以用来存放附魔（enchant）、属性（Attributes）、nbt等mc数据

```
display:
  name: ' &b附魔物品'
  material: CHAINMAIL_CHESTPLATE

properties:
 enchant:
   - 附魔1 等级
   - 附魔2 等级
 attributes:
   - xxx
 nbt:
   - xxx
 flag: #标志 可以隐藏一些描述、附魔光效等，不过这个其实可以归类到display
   - xxx
```

### 备注信息
> 需要额外说明的内容

附魔（Enchant）：被注册进bukkit的附魔类型
https://minecraft.fandom.com/zh/wiki/%E9%99%84%E9%AD%94
