### ISSUE TITLE
🐛 [BUG][1.13+] 1.13版本及以上无法正常使用AF创建命令

### ISSUE THREAD

**Issue by luoxiawuchen** [rokukoo/AzureFlow-issues#9]
官方WIKI：https://rokuko.gitbook.io/azureflow
描述清晰，排版整洁，错误日志详细的反馈通常会优先处理

### 反馈须知
- [X] 我已详细查阅wiki
- [X] 我已正确安装相关依赖

### 服务端类型
> 请填写您的服务端类型与Minecraft版本
> 如：spigot-1.16.5、paper-1.18.2

spigot-1.16.5
---------------------------------------

### 错误描述
> 请详细地描述您遇到的问题

使用/af create 创建物品后，文件能够正常生成，但无法被正常/af get 物品ID 获取（命令补齐中也不会显示新创建的物品ID）
打开文件，发现生成的内容为：
```
display:
  material: LEGACY_AIR
internal:
  uuid: 9663d471-20cf-464e-a28a-745ca71f9470
  alias:
  - ctest
```
需要修改material，将"LEGACY_"去除，并重载插件后，物品才能够被正常载入
可能的原因：高低版本的物品ID存在差异，创建时生成了旧版的材质ID

### 错误日志
> 建议将错误日志上传至 https://paste.ubuntu.com/
> 并以链接形式提交

无

### 备注信息
> 需要额外说明的内容

无
